[package]
name = "periodic-table-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
nom = "7.1.3"
once_cell = "1.20.2"
regex = "1.11.1"
shell-escape = "0.1.5"
